baseURL = "https://thekiller.net/"
languageCode = "en-us"
title = "Steve the Killer"
theme = "terminal"

[params]
  themeColor = "orange"
  fullWidthTheme = false
  centerTheme = true
  title = "Steve the Killer"
  subtitle = "Field tech. Analog film enthusiast. Based in Los Angeles."
  customCSS = ["css/custom.css"]
  menuItems = [
    { name = "Software", url = "/software/" },
    { name = "Blog", url = "/blog/" },
    { name = "Photos", url = "/photos/" }
  ]
  readMore = "Read more"
  dateFormat = "January 2, 2006"

[[menu.main]]
  name = "Software"
  url = "/software/"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 2

[[menu.main]]
  name = "Photos"
  url = "/photos/"
  weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
